/*
* Task1 HTTP1.0:
*    Используя программу telnet, выполните запрос к localhost на порт 8080 в терминале
*    онлайн редактора. Параметры запроса: глагол get, страница /about, протокол http 1.0.
*/

// Solution:
telnet localhost 8080

GET /about /HTTP/1.0


/*
* Task2 HTTP1.1:
*    Выполните запрос к hexlet.local (расположен на localhost) на порт 8080.
*    Параметры запроса: глагол get, страница /, протокол http 1.1;
*/

// Solution:
telnet localhost 8080

GET / HTTP/1.1
Host: hexlet.local


/*
* Task3 message-body:
*    Выполните запрос к hexlet.local (расположен на localhost) на порт 8080.
*    Параметры запроса: глагол post, страница /upload, протокол http 1.1, тело: my request body.
*    Не забудьте установить заголовки необходимые для отправки body;
*/

// Solution:
telnet localhost 8080

POST /upload HTTP/1.1
Host: hexlet.local
Content-Type: text/plain
Content-Length: 15

my request body


/*
* Task4 Sending form data:
*    Выполните авторизацию на сайте hexlet.local (расположен на localhost:8080).
*    Для этого отправьте следующие данные формы: username со значением admin, password со
*    значением secret на урл /session/new. Используйте глагол post
*    и тип application/x-www-form-urlencoded;
*/

// Solution:
telnet localhost 8080

POST /session/new HTTP/1.1
Host: hexlet.local
Content-Type: application/x-www-form-urlencoded
Content-Length: 30

username=admin&password=secret


/*
* Task5 Query String:
*    Выполните запрос к hexlet.local (расположен на localhost) на порт 8080.
*    Передайте в строке запроса следующие параметры: key равный value и another_key
*    равный another_value. Параметры запроса: глагол get, страница /, протокол http 1.1;
*/

// Solution:
telnet localhost 8080

GET /?key=value&another_key=another_value HTTP/1.1
Host: hexlet.local


/*
* Task6 HTTP Basic Authentication:
*    Авторизуйтесь на hexlet.local:8080 (расположен на localhost).
*    Параметры запроса: глагол get, страница /admin, протокол http 1.1,
*    имя пользователя Aladdin, пароль open sesame;
*        Подсказка
*        Для кодирования логина и пароля используйте следующую команду в терминале:
*            printf 'username:password' | base64
*/

// Solution:
printf 'Aladdin:open sesame' | base64 // QWxhZGRpbjpvcGVuIHNlc2FtZQ==

telnet localhost 8080

GET /admin HTTP/1.1
Host: hexlet.local
Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==


/*
* Task7 Cookies:
*    Выполните запрос к hexlet.local (расположен на localhost) на порт 8080.
*    Параметры запроса: глагол get, страница /account, протокол http 1.1,
*    куки name со значением user и secret со значением secret_hash;
*/

// Solution:
telnet localhost 8080

GET /account HTTP/1.1
Host: hexlet.local
Cookie: name=user; secret=secret_hash

